// The rows of the controls help (openHelp in hud.ts), in the order it shows them: a key or an emoji, and
// what it does. A new control is a new row here.

import { IS_MAC } from './termkeys';

export const HELP_ROWS: readonly (readonly [string, string])[] = [
  ['W A S D', 'Walk (hold Shift to run)'],
  ['Space', 'Jump'],
  ['☕', 'Press E at the coffee machine in the kitchen for a minute of quicker walking and higher jumps. Three cups in a row gives you the jitters'],
  ['Mouse', 'Look around in first person (click to capture the mouse, Esc to free it)'],
  ['Click / E', "Use what you look at: hire a worker, open its terminal, read a board, call a meeting in the meeting room, watch the TV, put a song on the jukebox (or paste a YouTube link, which plays on the lounge TV with its sound as the floor's music), tee off from the balcony (a floor with two tees has room for two at once), sit on a couch, a beanbag, a chair or the balcony bench (walk off to get up)"],
  ['👥', 'Click someone under "In the office" to walk over to them (on another floor, you ride the elevator first). The line under their name says what they have open or where they are'],
  ['🛗', 'Every project is a floor: step into the elevator on the north wall and press E (or click the project name, top left) to go to another one (admins add a project there too). It goes down to the garage too, and back up from there'],
  ['🤖', 'An agent stands by the issues board, the PR board and the task queue. Press E at one and type what you want: it runs as an agent that knows that board. O there opens its terminal, X sends it home'],
  ['📝', 'The whiteboard on wheels between the desks and the lounge: press E to draw on it with everyone on your floor, live. What you draw stays up on the board'],
  ['🕹️', 'The arcade cabinet in the lounge plays Minesweeper, Blockfall, 2048 and Snake, the same games as the boss’s monitor: E goes up to its screen, ↑ ↓ and Enter (or a click) pick one, and 🎮 Games goes back to the list. Each game has one high-score table for the whole building, wherever it’s played. Everyone on the floor sees your game on the cabinet, and E there watches whoever is playing. One of your workers needing input stops it'],
  ['🎉', 'Whenever a pull request merges, the gong next to the PR board rings, confetti rains down all over the floor and every worker gets up on its desk for a quick dance. Walk up to the gong and press E to bang it yourself'],
  ['N', "Next worker that needs you: go to whoever needs input (they have a red beacon over their desk, and a banner up top says what each is asking), then whoever is done and nobody's looked at, longest-waiting first, and again for the next one. Arrows at the edge of the screen point to the ones out of sight"],
  ['🏀', 'The hoop on the west wall, by the exit door: E at the ball picks it up. Hold E (or the mouse, in first person) and let go when the meter is in the green to sink it. In first person it goes where you look. Q drops it. Everyone on your floor sees your shot'],
  ['🐷', 'The scoreboard beside the hoop has the building’s longest shots, one a person (E at it shows all ten, when each went in, and who’s won the most games of PIG). With someone else at the court, P (with the ball, or at the board) asks them to play PIG: sink one from anywhere and they have to sink it from the ring on the floor, or take a letter. Miss your own and the lead goes over. Spell PIG and you lose'],
  ['🏎️', "The Lambos and Ferraris in the garage: E at one gets you behind the wheel, or beside whoever's driving it. W is the gas, S brakes and reverses, A and D steer, Space brakes, H honks and E gets you out. Everyone on your floor sees you drive by"],
  ['🏙️', 'Main Street, out front: Friday Tower’s street, with plots either side for other businesses. E at a plot’s sign (its FOR LEASE board, or a claimed plot’s gate or lobby doors), or at the map board in Friday Park across the road, opens the Main Street window: who’s where, and for street admins (the office’s admins) claiming a plot for a business as a building site or the shell of its tower in its colors, changing it, or giving it back'],
  ['⛳', 'Putt Street, the nine-hole mini golf course on Main Street: E at the putter rack in its kiosk joins a group (up to four) or starts one; the group’s starter can tee off early with E there again, and E twice there hands your putter back. On your turn walk up to your ball and press E. The mouse (or A and D) aims; hold Space and let go when the meter, running up and back down, is where you want it. E or Esc steps away. Water, or a ball off the felt, costs a stroke; six strokes and you’re picked up. The record board keeps the course record, the best on each hole and the holes in one'],
  ['🚁', 'Friday One, the helicopter on its pad in Friday Park: street admins fly it, and anyone can ride along. E by a door gets in, and out once it’s down. Space spins the rotor up and climbs, Shift sinks, W and S fly forward and back, A and D turn (the arrow keys too), the mouse looks round, C switches between the chase and cockpit views and the wheel pulls the chase camera in or out. It sets down only slowly, on clear ground or its pad, and never on anyone. Everyone on every floor sees and hears it'],
  ['🍸', 'The elevator goes up to the rooftop bar: a DJ playing drum and bass under the lights, and the city all around. Press E at the bar for a drink (it goes to your head for a bit) and at the DJ booth for the air horn'],
  ['🎯', 'Up on the roof, in the corner past the DJ: a dart board and an axe-throwing lane. E at either steps up to the line. The mouse (or the arrow keys) aims, and your hand wanders more after a few drinks. Hold Space (or the mouse button) and let go in the green: three darts a visit, five axes a round, chalked up for everyone up there. E steps back'],
  ['👑', 'The boss’s desk, up in the boss’s office (on a floor that has one): sit in the boss’s chair and the desk’s menu opens (E opens it again). Share your screen, or play Minesweeper, Blockfall, 2048 or Snake on the monitor. Two chairs across the desk are for whoever’s meeting with you: a second monitor faces them and shows what yours does, E from one brings it up big, and whoever sits down second is put on a call with the other side (V to talk, M to mute). Getting up stops what the desk started'],
  ['📺', 'A video screen on the floor plays the videos in that floor’s .agent-office/media folder, on a loop, with no sound. E at one watches what’s on it in a window, with sound'],
  ['▶️', 'A video screen can follow YouTube channels instead: admins list the channels in the floor’s setup (Channels to watch) and set a screen to “Channels we watch” in the office builder. It plays their newest videos, newest first, through YouTube’s own player with no sound, and says under each who it’s from. E at one watches it in a window, with sound'],
  ['🥊', 'Things to play with, wherever a floor has them: E punches the punching bag, drops a can from the vending machine, spins the prize wheel, swings at the high striker, kicks off a point of foosball, or starts a ping-pong rally (Space hits the ball back). Step onto a trampoline to bounce (hold Space to go higher) or onto the dance mat to light its tiles'],
  ['🥃', 'A whisky cabinet, wherever a floor has one: E there pours you a dram of The Macallan Litha from its decanter. E sips it when there’s nothing in front of you to use, and empty, the glass goes back on the tray'],
  ['K', 'Cheers: with a dram in hand and someone within about 2 m holding one of theirs, raise your glass to them. Within arm’s reach (about 1.3 m) your glasses meet between you with a clink; further off they’re raised to each other. “Cheers” pops up over your heads, and now and then the floor hears who raised a glass'],
  ['Drag / wheel', 'Orbit and zoom the camera in third person'],
  ['P', 'Prompt: give a task to a new or existing worker at the desk you face'],
  ['C', 'Changes: what the worker at the desk you face changed — files and diff, commit, discard, open a PR'],
  ['B', 'Open a shared shell (dev servers, git, tests) at an empty desk'],
  ['U', 'Admins: the office builder. From up over the room, drag the desks and the furniture about, add more from the catalog (team desks you sit at to share your screen, walls, glass and doorways to make rooms, video screens, a stock ticker, things to play with, sofas, plants, rugs, signs, paintings of the floor’s own pictures on any wall), repaint the room, choose its structure (one level, the corner loft or the big mezzanine; the boss’s office or an empty loft; a kitchen or none; wood walls; its tees), furnish its upstairs on the Upstairs level, and save it for everyone on the floor'],
  ['R', 'Resume a sleeping worker'],
  ['X', 'Send a worker home (frees the desk)'],
  ['L', 'Hang a big sign over the desk you face ("Operations", "Code cleanup"), or change or take down the one there'],
  ['🚧', 'Room to grow, for admins: E at the sign on the north wall past the gong knocks through into a back office with 2 more desks, and again for 2 more. The same sign walls a row back up'],
  ['F', 'Hang a picture from the web on a wall. Look at a picture and press E to move, edit or take it down'],
  ['Q', 'Put back the issue card in your hands (E at a note on the issues board, or ✋ Pick it up in an issue; then E at an empty desk, a worker or the queue board), or drop the basketball'],
  ['🐶', 'Walk up to the office dog and press E to pet it. When a worker needs input, it runs to that desk and barks. Name it in ⚙️ Settings'],
  ['🐐', 'Marc, the office goat, lives on the bottom floor: he ambles about, grazes on the plants, nibbles the rugs and butts the punching bag. Walk up to him and press E to pet him: he bleats, and follows you about for a minute. An admin he follows into the elevator too, and then lives on whichever floor they rode to'],
  ['O', 'Open a pull request for a worker on its own branch, or see the one it has'],
  ['T', 'Chat'],
  ['G / 1–6', 'Emote: hold G, point at one and let go (or tap G and click one), or press 1–6: wave, thumbs up, clap, dance, point, facepalm. Everyone on your floor sees it'],
  ['/', 'Search the chat and every terminal on your floor, back to before the office last restarted'],
  [IS_MAC ? '⌘K' : 'Ctrl+K', 'Command palette: type a few letters to find a worker, issue, PR, service, board, teammate or action. Enter opens it, Shift+Enter walks you over to it first'],
  ['V', 'Join voice. In voice, hold V to talk (push to talk): you’re muted once you let go. Leave voice from the ☰ menu'],
  ['M', 'Mute or unmute your mic in voice. ⚙️ Settings can have you join muted, for push to talk'],
  ['Ctrl+Space', 'Dictate: in a worker’s terminal or a prompt box, hold Ctrl+Space (or the 🎤) and talk, and what you said is typed in when you let go, for you to read over and send. A quick tap leaves it listening until you tap again. The browser does the listening (Chrome, Edge and Safari can), so there’s nothing to install'],
  ['Tab', 'The ☰ menu, top right: every window, and what shows on screen. Pin what you use most to the top bar'],
  ['Esc', 'Close any window and get back to looking around'],
  ['Ctrl + [', 'Send Esc to a terminal instead, to close a menu like Claude’s /skills or interrupt Claude. ⎋ Esc in the terminal’s header does the same'],
  ['⚙️', 'Settings (in the ☰ menu): switch between first and third person'],
];
