import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import { listSkills, readSkill, saveSkill } from '../src/server/skill-library/library.js';
import { skillLibraryRoute } from '../src/server/http/routes/skill-library.js';
function fixture(t:any){const floor=fs.mkdtempSync(path.join(os.tmpdir(),'skill-lib-'));t.after(()=>fs.rmSync(floor,{recursive:true,force:true}));const root=path.join(floor,'skill-library');fs.mkdirSync(path.join(root,'skills','writer'),{recursive:true});fs.writeFileSync(path.join(root,'skills','writer','SKILL.md'),'---\nname: Writer\ndescription: Write clearly\nlibrary-category: Writing\n---\n# Writer\nOriginal instructions\n');const git=(a:string[])=>execFileSync('git',a,{cwd:root,stdio:'pipe'});git(['init','-b','main']);git(['add','.']);git(['-c','user.name=Test','-c','user.email=test@local','commit','-m','Import skills']);return{floor,root,git};}
test('library lists real skills and records edits and restores as new Git versions',t=>{const{floor}=fixture(t);const list=listSkills(floor);assert.equal(list[0].name,'Writer');assert.equal(list[0].category,'Writing');const original=readSkill(floor,'writer');const updated=saveSkill(floor,'writer',original.text+'New guidance\n',original.revision,'Clarify guidance');assert.equal(updated.versions.length,2);assert.match(updated.text,/New guidance/);const old=readSkill(floor,'writer',original.revision);assert.doesNotMatch(old.text,/New guidance/);assert.match(old.diff!,/New guidance/);const restored=saveSkill(floor,'writer','',updated.revision,'Return to original',original.revision);assert.equal(restored.versions.length,3);assert.equal(restored.text,original.text);assert.throws(()=>saveSkill(floor,'writer','x',original.revision,'Stale'),/changed/);});
test('library blocks traversal, symlinks, unsafe revisions and dirty working trees',t=>{const{floor,root}=fixture(t);assert.throws(()=>readSkill(floor,'../writer'),/Invalid/);assert.throws(()=>readSkill(floor,'writer','HEAD~1'),/Invalid/);const d=readSkill(floor,'writer');fs.writeFileSync(path.join(root,'note.txt'),'Uncommitted');assert.throws(()=>saveSkill(floor,'writer','Changed',d.revision,'Change'),/uncommitted/);fs.symlinkSync(os.tmpdir(),path.join(root,'skills','escape'));assert.throws(()=>readSkill(floor,'escape'),/links/);});
test('the library route is restricted to AI Innovators and admin mutations',async t=>{const{floor}=fixture(t);let status=0,body:any;const ctx:any={floors:new Map([['ai-innovators',{id:'ai-innovators',dir:floor}],['other',{id:'other',dir:floor}]]),meOf:()=>({admin:false}),cfg:{}};const res:any={writeHead(n:number){status=n;},end(s:string){body=JSON.parse(s);}};const run=(method:string,f:string)=>skillLibraryRoute.handle(ctx,{req:{method,headers:{}} as any,res,url:new URL(`http://localhost/api/skill-library?floor=${f}`),path:'/api/skill-library',session:{}});await run('GET','ai-innovators');assert.equal(status,200);assert.equal(body.skills.length,1);await run('POST','ai-innovators');assert.equal(status,403);await run('GET','other');assert.equal(status,404);ctx.meOf=()=>({admin:true});await run('POST','ai-innovators');assert.equal(status,403);});
